version: "3.8"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/django_app:/usr/src/app
      - django_static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./backend/.env
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  # react:
  #   build:
  #     context: ./frontend
  #     dockerfile: dev.Dockerfile
  #     args:
  #       - API_SERVER=${ENV_API_SERVER}
  #   volumes:
  #     - react_static_volume:/usr/src/app/build/static
  #   expose:
  #     - 3000
  #   env_file:
  #     - .env
  #   command: serve -s build -l 3000
  #   depends_on:
  #     - django

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
      # - react_static_volume:/usr/src/app/react_files/static
    ports:
      - 8000:8000
    # depends_on:
    #   - react
    restart: always

volumes:
  postgres_data:
  django_static_volume:
  # react_static_volume: