###########
# BUILDER #
###########

# pull official base image
FROM python:3.11.4-slim-bullseye as builder

# set work directory 
WORKDIR /usr/src/app

# set environment variables 
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt


#########
# FINAL #
#########

# pull official base image
FROM python:3.11.4-slim-bullseye

# installing netcat (nc) since we are using that to listen to postgres server in entrypoint.sh
RUN apt-get update && apt-get install -y --no-install-recommends netcat && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install dependencies
COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# set work directory
WORKDIR /usr/src/app

# copy our django project
COPY ./django_app .

# copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/entrypoint.sh

# run entrypoint.sh
RUN chmod +x /usr/src/entrypoint.sh
ENTRYPOINT ["/usr/src/entrypoint.sh"]